const express=require('express')
const { getAllReservations, makeReservation, cancelReservation,getClientReservations } = require('../Controllers/ReservationController')
const {protectClient}=require('../Middleware/ClientMiddleware')
const {protectAdmin}=require('../Middleware/AdminMiddleware')
const router = express.Router()
router.get('/',protectAdmin,getAllReservations)
router.get('/:client_id', protectClient,getClientReservations)
router.post('/:trip_id/:client_id',protectClient,makeReservation)
router.delete('/:reservation_id/:trip_id/:client_id',cancelReservation)
module.exports=router